[WIP] Cloud Functions for Users
GTHC/benchburner pull request #1
Opened 2018-09-16 22:38 UTC by amanmibra

## Purpose
Create and set up user-related cloud functions, including auth, setting user data, etc.

## To-Do 
_Please add more if you can think of any_
- [x] Add new user to collection
- [ ] Add user-specific info to docs when signing up
- [ ]  Set up queries to get user data from HTTPS triggers

## How to test
Ask @amanmibra

2018-09-18 21:40 UTC, mafuvadze commented on functions/src/user.ts
> +import * as functions from 'firebase-functions';
Not a fan of import *
I prefer to import only what you need. This also has slight performance issues

2018-09-18 21:42 UTC, mafuvadze commented on functions/src/user.ts
> +    console.log('ref value', ref)
Really bad to have console.logs in production code. I'd think about making a logger. Would also allow us to collect better analytics for errors and warnings in we have a central place to report information/errors/warnings

2018-09-18 21:43 UTC, mafuvadze requested changes
Looks good, just a couple nits

2018-09-21 02:48 UTC, amanmibra commented on functions/src/user.ts
> +import * as functions from 'firebase-functions';
This is necessary for the time-being as I am new to this library and I'm getting used to what triggers/functionalities of the library is needed and not needed. Once that period of discovery and adjustment has passed, then I will work on importing only the dependencies I need.

2018-09-21 02:48 UTC, amanmibra commented on functions/src/user.ts
> +import * as functions from 'firebase-functions';
Thanks for pointing it out

2018-09-21 02:48 UTC, amanmibra commented
@mafuvadze this PR is nowhere near finished, I will ping you later when the review is actually needed

2018-09-21 05:35 UTC, mafuvadze commented
Sounds good! Just add TODOs so you don't forget to fix them later

2018-09-21 05:35 UTC, mafuvadze approved these changes

2018-09-23 04:21 UTC, amanmibra commented
@mafuvadze Pls approve

2018-09-23 22:52 UTC, merged

2018-09-24 01:57 UTC, amanmibra commented
Did you actually check the new commits? @mafuvadze

2018-09-24 01:57 UTC, amanmibra commented
Please make sure you do a review right before you merge because I made a bunch of changes.